const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

module.exports = {
  // devtool: "none",
  mode: 'development',
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader",
        }
      },
      {
        test: /\.(sa|sc|c)ss$/,
        use: [
          {
            loader: MiniCssExtractPlugin.loader,
            options: {
            // you can specify a publicPath here
            // by default it uses publicPath in webpackOptions.output
              hmr: process.env.NODE_ENV === 'development',
            },
          },
          {loader: "css-loader"},  // 2. Turns css to js
          {loader: "sass-loader"} // 1. Turns scss to css
        ],

      }
    ]
  },
  plugins: [
    //     new HtmlWebpackPlugin({ // Need this to support hot reloading
    //     title: "Dat Le's Portfolio",
    //     inject: true, // Inject all files generated by webpack
    //     template: './template.html',
    //     exludeChunks: ['manifest']
    // }),
    new MiniCssExtractPlugin({filename: 'styles.css'}),
    new webpack.optimize.OccurrenceOrderPlugin(), // All 3 necesary for HMR
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoEmitOnErrorsPlugin(),
    new webpack.DefinePlugin({ // For scss
      'process.env': {
          WEBPACK: JSON.stringify(true),
      }
    })
  ],
};